# esercizio covid

In [8]:
import numpy as np
import pandas as pd
import seaborn as sb
from matplotlib import pyplot as plt

In [9]:
datagen = pd.read_csv('/Users/User/OneDrive - Università degli Studi di Trieste/3° anno/Tecniche di Rappresentazione e Modellizzazione Dati/DatiCovid', delimiter = ',',header=0)
datagen

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,...,note,ingressi_terapia_intensiva,note_test,note_casi,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido,codice_nuts_1,codice_nuts_2
0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-02-24T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-02-24T18:00:00,ITA,18,Calabria,38.905976,16.594402,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-02-24T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-24T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28282,2023-11-01T17:00:00,ITA,19,Sicilia,38.115697,13.362357,146,7,153,3074,...,NaN,1.0,NaN,NaN,541709.0,1291232.0,5480998.0,11465011.0,ITG,ITG1
28283,2023-11-01T17:00:00,ITA,9,Toscana,43.769231,11.255889,262,9,271,2834,...,NaN,1.0,NaN,NaN,724270.0,905087.0,7120707.0,9975918.0,ITI,ITI1
28284,2023-11-01T17:00:00,ITA,10,Umbria,43.106758,12.388247,117,2,119,1256,...,- Si fa presente che 1 dei ricoveri non UTI ap...,0.0,NaN,NaN,160191.0,291138.0,1761055.0,3364731.0,ITI,ITI2
28285,2023-11-01T17:00:00,ITA,2,Valle d'Aosta,45.737503,7.320149,19,1,20,82,...,NaN,1.0,NaN,NaN,16350.0,35451.0,146237.0,453986.0,ITC,ITC2
28286,2023-11-01T17:00:00,ITA,5,Veneto,45.434905,12.338452,345,21,366,7881,...,Nei valori riportati per le terapie intensive ...,2.0,NaN,NaN,1108127.0,1668787.0,11979930.0,26663968.0,ITH,ITH3

In [10]:
data = datagen[datagen["denominazione_regione"]=="Abruzzo"]
data

,data,stato,codice_regione,denominazione_regione,lat,long,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,...,note,ingressi_terapia_intensiva,note_test,note_casi,totale_positivi_test_molecolare,totale_positivi_test_antigenico_rapido,tamponi_test_molecolare,tamponi_test_antigenico_rapido,codice_nuts_1,codice_nuts_2
0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2020-02-25T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2020-02-26T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,2020-02-27T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,1,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,2020-02-28T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,1,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28182,2023-10-28T17:00:00,ITA,13,Abruzzo,42.351222,13.398438,61,1,62,2804,...,Il dato ''incremento casi confermati'' è compo...,0.0,NaN,NaN,256093.0,414413.0,2633814.0,4961123.0,ITF,ITF1
28203,2023-10-29T17:00:00,ITA,13,Abruzzo,42.351222,13.398438,61,1,62,2839,...,Il dato ''incremento casi confermati'' è compo...,0.0,NaN,NaN,256117.0,414442.0,2633956.0,4961548.0,ITF,ITF1
28224,2023-10-30T17:00:00,ITA,13,Abruzzo,42.351222,13.398438,59,1,60,2804,...,Il dato ''incremento casi confermati'' è compo...,0.0,NaN,NaN,256152.0,414457.0,2634024.0,4961687.0,ITF,ITF1
28245,2023-10-31T17:00:00,ITA,13,Abruzzo,42.351222,13.398438,65,2,67,2822,...,Il dato ''incremento casi confermati'' è compo...,1.0,NaN,NaN,256213.0,414549.0,2634139.0,4962427.0,ITF,ITF1
28266,2023-11-01T17:00:00,ITA,13,Abruzzo,42.351222,13.398438,65,2,67,2876,...,Il dato ''incremento casi confermati'' è compo...,0.0,NaN,NaN,256239.0,414603.0,2634374.0,4962913.0,ITF,ITF1

In [15]:
datadef = data[['data','totale_positivi']]
datadef

                      data  totale_positivi
0      2020-02-24T18:00:00                0
21     2020-02-25T18:00:00                0
42     2020-02-26T18:00:00                0
63     2020-02-27T18:00:00                1
84     2020-02-28T18:00:00                1
...                    ...              ...
28182  2023-10-28T17:00:00             2866
28203  2023-10-29T17:00:00             2901
28224  2023-10-30T17:00:00             2864
28245  2023-10-31T17:00:00             2889
28266  2023-11-01T17:00:00             2943

[1347 rows x 2 columns]